// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

namespace CM.Utility
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseJson<T>
    {
        [JsonProperty("code")]
        public long Code { get; set; }

        [JsonProperty("msg")]
        public string Msg { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("data")]
        public IEnumerable<T> Data { get; set; }

        public ResponseJson()
        {
            this.Code=200;
            this.Msg="ok";
            this.Count=0;
        }

    }

    
}
